[package]
name = "starcil-terminal"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
portable-pty.workspace = true
vt100.workspace = true
tracing.workspace = true
starcil-domain.workspace = true
