[package]
name = "starcil-integrations"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
toml_edit.workspace = true
tracing.workspace = true
starcil-domain.workspace = true
starcil-agents.workspace = true

[dev-dependencies]
tempfile.workspace = true
